// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "b511dffd-3abe-43f2-9f5f-6104dda68946";

const char APPEUI[]   = SECRET_APP_EUI;
const char APPKEY[]   = SECRET_APP_KEY;

void onCh1Change();
void onTEMPChange();

float ch1;
CloudTemperatureSensor tEMP;

void initProperties(){
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(ch1, 1, READWRITE, ON_CHANGE, onCh1Change);
  ArduinoCloud.addProperty(tEMP, 2, READWRITE, ON_CHANGE, onTEMPChange);

}

LoRaConnectionHandler ArduinoIoTPreferredConnection(APPEUI, APPKEY, _lora_band::AS923);
